language: r
sudo: required
dist: trusty

cache: packages

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R -e 'tfprobability::install_tfprobability(version = "0.7.0", tensorflow = "2.1.0")'
  - R -e 'tensorflow::tf_config()'

r_packages:
  - devtools
  - covr
  - testthat
  - knitr
  - rmarkdown

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
